### PR TITLE
Project refactoring

### PR DESCRIPTION
**Pull request by elshize**

### CODE REVIEW

**Comment by MarcoMontaltoMonella** [comment]
I think you forgot to add a `.gitignore` file

**Comment by elshize** [comment]
> I think you forgot to add a `.gitignore` file

It's right here: https://github.com/pisa-engine/Porter2/blob/master/.gitignore

**Comment by elshize** [comment]
@amallia how about a review?

**Comment by amallia** [comment]
LGTM
the only question I have is why we do `include/Porter2.hpp` instead of `include/Porter2/Porter2.hpp`.
Most libs, for example CLI11, use the latter one.

**Comment by elshize** [comment]
I figured it was overkill for one header file but I don't have strong feelings about either, so if you like it in a folder better, thank I can easily change it back.

**Pull request merged**
